services:
  face-api:
    build: .
    container_name: deepface_api
    restart: always
    ports:
      - "8000:8000"
    volumes:
      # Usar rutas relativas para evitar problemas con espacios
      - ./imagenes_base:/app/imagenes_base
      - ./tmp_uploads:/app/tmp_uploads
      # Crear archivos JSON si no existen, usando bind mounts relativos
      - ./data:/app/data
    environment:
      # Variables de entorno para configurar rutas
      - USERS_FILE=/app/data/usuarios.json
      - TERMINAL_REQUESTS_FILE=/app/data/solicitudes_registro.json
      - UBICACIONES_FILE=/app/data/ubicaciones.json
      - RECORDS_FILE=/app/data/registros.json

  nginx:
    image: nginx:alpine
    container_name: deepface_api_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/logs:/var/log/nginx
      - ./static:/app/static
    depends_on:
      - face-api